### PR TITLE
Update main.cpp

### PR DESCRIPTION
**Pull request by CrackTC**
Use English as main lang

### CODE REVIEW

**Comment by Cheny233** [comment]
建议将修改的内容移至English.cpp

**Comment by jinzhijie** [comment]
@CrackTC You can translate `main.cpp` into English in `english.cpp`, and create a new PR

**Comment by SerinaNya** [comment]
> Use English as main lang

you should rename the `main.cpp` to `english.cpp`

**Comment by CrackTC** [comment]
okk

**Comment by Cheny233** [comment]
And create `main.cpp` again.

**Pull request merged**
